-- AlterTable
ALTER TABLE "Post" ADD COLUMN     "authorCredentials" TEXT,
ADD COLUMN     "authorExperienceYrs" INTEGER,
ADD COLUMN     "authorProfileUrl" TEXT,
ADD COLUMN     "citations" TEXT[],
ADD COLUMN     "contentVersion" TEXT,
ADD COLUMN     "editorialPolicyUrl" TEXT,
ADD COLUMN     "hasDisclaimer" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "intent" TEXT,
ADD COLUMN     "lastMedicalUpdate" TIMESTAMP(3),
ADD COLUMN     "mainEntity" TEXT,
ADD COLUMN     "medicalBoardUrl" TEXT,
ADD COLUMN     "medicalConditions" TEXT[],
ADD COLUMN     "medicalReviewDate" TIMESTAMP(3),
ADD COLUMN     "medicalSpecialty" TEXT,
ADD COLUMN     "medications" TEXT[],
ADD COLUMN     "publisherLogoUrl" TEXT,
ADD COLUMN     "publisherName" TEXT,
ADD COLUMN     "publisherUrl" TEXT,
ADD COLUMN     "reviewedBy" TEXT,
ADD COLUMN     "reviewerCredentials" TEXT,
ADD COLUMN     "riskLevel" TEXT,
ADD COLUMN     "symptoms" TEXT[],
ADD COLUMN     "targetAudience" TEXT,
ADD COLUMN     "treatments" TEXT[],
ALTER COLUMN "updatedAt" DROP DEFAULT,
ALTER COLUMN "dateModified" DROP DEFAULT;
